Fix/index creation
GSA/ckanext-geodatagov pull request #224
Opened 2022-10-06 21:55 UTC by robert-bryson

# Pull Request

Related to [LINK TO ISSUE]

## About

## PR TASKS

- [ ] The actual code changes.
- [ ] Tests written and passed.
- [ ] Any changes to docs?
- [ ] Bumped version number in [setup.py](https://github.com/GSA/ckanext-geodatagov/blob/1b1bad0b2ff06112e18c7f4f4fb1143baec1266a/setup.py#L13) (also checked on [PyPi](https://pypi.org/project/ckanext-geodatagov/#history)).

2022-10-18 19:17 UTC, FuhuXia requested changes

2022-10-18 19:17 UTC, FuhuXia commented on ckanext/geodatagov/cli.py
> +_INDICES = {"package": PackageSearchIndex}
```suggestion
```

2022-10-18 19:17 UTC, FuhuXia commented on ckanext/geodatagov/cli.py
> +_INDICES = {"package": PackageSearchIndex}
defined twice?

2022-10-18 19:26 UTC, FuhuXia commented
How big are the file uploads in total?

2022-10-18 20:32 UTC, robert-bryson commented
> How big are the file uploads in total?

The sitemap files appear to be about 200kb each. The ~30k records on catalog dev result in about 6mb of files. I haven't run on prod, but obviously it will be a much larger number in total.

2022-10-18 22:54 UTC, jbrown-xentity approved these changes

2022-10-19 12:58 UTC, FuhuXia approved these changes

2022-10-19 12:58 UTC, merged